[tool.poetry]
name = "base-converter"
version = "0.1.0"
description = "Convert decimal integers and floats to a new base equivalent"
authors = ["TonyGrif <TonyGriffin2000@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [
    {include = "src"},
]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.group.test.dependencies]
pytest = "^9.0.3"
pytest-cov = "^7.1"
tox = "^4.30"

[tool.poetry.group.dev.dependencies]
mypy = "^1.19"
black = "^26.3.1"
isort = "^6.1"
pylint = "^3.3"
ruff = "^0.15"
flake8-pyproject = "^1.2"

[tool.poetry.group.docs.dependencies]
sphinx = ">=7.0"
furo = "^2025.12.19"
sphinx-copybutton = "^0.5.2"

[tool.tox]
requires = ["tox>=4"]
env_list = ["py310", "py311", "py312", "py313", "py314"]

[tool.tox.env_run_base]
description = "Run the PyTest Suite."
skip_install = true
deps = ["poetry"]
commands_pre = [["poetry", "install", "--only", "main,test"]]
commands = [["poetry", "run", "pytest", "--cov"]]

[tool.pytest.ini_options]
testpaths = ["tests"]
log_cli = "True"

[tool.mypy]
files = ["src"]

[tool.isort]
profile = "black"

[tool.flake8]
max-line-length = 88
extend-ignore = ["E203", "E701"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
